{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.role.name }}
rules:
- resources:
    - "pods"
    - "nodes"
  verbs:
    - "get"
    - "watch"
    - "list"
  apiGroups:
    - ""
{{- end }}
