apiVersion: v1
kind: Secret
metadata:
  name: cloudthread-s3-creds
  namespace:  {{ .Release.Namespace }}
type: Opaque
data:
  role_arn: {{ .Values.cloudthread.role_arn | b64enc | quote }}
  role_external_id: {{ .Values.cloudthread.role_external_id | b64enc | quote }}
  {{- if (.Values.cloudthread.dst_bucket) }}
  dst_bucket: {{ .Values.cloudthread.dst_bucket | b64enc | quote }}
  {{- end }}
  stream_token: {{ .Values.cloudthread.stream_token | toString | b64enc | quote }}
  {{- if (.Values.cloudthread.key_id) }}
  key_id: {{ .Values.cloudthread.key_id | toString | b64enc | quote }}
  {{- end }}
  {{- if (.Values.cloudthread.key) }}
  key: {{ .Values.cloudthread.key | toString | b64enc | quote }}
  {{- end }}
